//go:build integration

package database

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"go-ispconfig/internal/model"
)

// TestCronModelRoundTrip inserts one realistic cron row into a migrated
// MariaDB schema and reads it back (add-cron-module task 1.1): the GORM
// column mapping must survive a real insert/scan cycle, not only the
// static DDL comparison of model_test.go.
func TestCronModelRoundTrip(t *testing.T) {
	dsnPrefix, container := StartMariaDB(t, "cronrt")
	MariaDBExec(t, container, "CREATE DATABASE cronrt CHARACTER SET utf8mb4")
	db, err := Open(dsnPrefix + "/cronrt?charset=utf8mb4&parseTime=True&loc=Local")
	require.NoError(t, err)
	needSeed, err := Migrate(db)
	require.NoError(t, err)
	require.True(t, needSeed)

	// A parent web_domain is required because cron.parent_domain_id is
	// NOT NULL with no default. Use the model-level id the autogenerated
	// insert produces.
	parent := model.WebDomain{
		SysUserID: 1, SysGroupID: 1,
		SysPermUser: "riud", SysPermGroup: "riud", SysPermOther: "",
		ServerID: 1, IPAddress: "*", Domain: "example.com", Type: "vhost",
		DocumentRoot: "/var/www/clients/client1/web1",
		SystemUser:   "web1", SystemGroup: "client1",
		CGI: "n", SSI: "n", Suexec: "y", Ruby: "n", Python: "n", Perl: "n",
		SSLLetsencryptExclude: "n", PHPFPMChroot: "n", BackupEncrypt: "n",
		TrafficQuotaLock: "n", EnablePagespeed: "n", ProxyProtocol: "n",
		DeleteUnusedJailkit: "n", DisableSymlinknotowner: "n",
		PHP: "php-fpm", PHPFPMUseSocket: "y", PM: "dynamic",
		PMMaxChildren: 10, PMStartServers: 2, PMMinSpareServers: 1, PMMaxSpareServers: 5,
		PMProcessIdleTimeout: 10,
		SSL:                  "n", SSLLetsencrypt: "n", RewriteToHTTPS: "n",
		SeoRedirect: "non_www_to_www", Subdomain: "www", Active: "y",
		HTTPPort: 80, HTTPSPort: 443,
	}
	require.NoError(t, db.Create(&parent).Error)

	job := model.Cron{
		SysUserID: 1, SysGroupID: 1,
		SysPermUser: "riud", SysPermGroup: "riud", SysPermOther: "",
		ServerID: 1, ParentDomainID: parent.DomainID,
		Type:     model.CronTypeURL,
		Command:  "https://example.com/cron.php",
		RunMin:   "*/5",
		RunHour:  "*",
		RunMday:  "*",
		RunMonth: "*",
		RunWday:  "*",
		Log:      "y",
		Active:   "y",
	}
	require.NoError(t, db.Create(&job).Error)
	require.NotZero(t, job.ID, "autoincrement id must be assigned")

	var got model.Cron
	require.NoError(t, db.Take(&got, job.ID).Error)
	assert.Equal(t, "url", got.Type)
	assert.Equal(t, "https://example.com/cron.php", got.Command)
	assert.Equal(t, "*/5", got.RunMin)
	assert.Equal(t, "y", got.Log)
	assert.Equal(t, "y", got.Active)
	assert.EqualValues(t, parent.DomainID, got.ParentDomainID)
}
