package dns

// Golden-file tests (bind-zone-generation spec): realistic dns_soa/dns_rr
// fixtures rendered through RenderZone and compared byte-for-byte against
// golden/<name>.golden. The expected outputs follow the PHP pipeline
// (tpl.inc.php rendering bind_pri.domain.master after the
// bind_plugin.inc.php soa_update pre-processing); php-cli was not
// available in the build environment, so the files were generated by this
// implementation and verified line by line against the PHP semantics —
// the same procedure as the internal/mastertpl golden suite. To
// regenerate after an INTENDED change:
//
//	go test ./internal/dns -run TestGolden -update
//
// and review the diff. Never accept a diff without understanding it.

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

var update = flag.Bool("update", false, "rewrite golden files with current render output")

func checkGolden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("golden", name+".golden")
	if *update {
		require.NoError(t, os.MkdirAll("golden", 0o755))
		require.NoError(t, os.WriteFile(path, []byte(got), 0o644))
		return
	}
	want, err := os.ReadFile(path)
	require.NoError(t, err, "missing golden file; run: go test ./internal/dns -run TestGolden -update")
	require.Equal(t, string(want), got, "rendered output differs from golden file %s", path)
}

// goldenSoa mirrors a dns_soa datalog payload (numbers arrive as JSON
// float64 in production; ints render identically).
func goldenSoa() map[string]any {
	return map[string]any{
		"id": 1, "origin": "example.com.", "ns": "ns1.example.com.",
		"mbox": "admin.example.com.", "serial": 2026080105,
		"refresh": 7200, "retry": 540, "expire": 604800,
		"minimum": 3600, "ttl": 3600, "active": "Y",
	}
}

// TestGoldenZoneAllTypes covers every record type handled by
// bind_pri.domain.master plus empty-name/TTL-0 shorthand.
func TestGoldenZoneAllTypes(t *testing.T) {
	records := []map[string]any{
		rr("", "NS", "ns1.example.com.", 0, 3600),
		rr("", "NS", "ns2.example.com.", 0, 3600),
		rr("", "A", "192.0.2.10", 0, 0),
		rr("www", "A", "192.0.2.10", 0, 3600),
		rr("", "AAAA", "2001:db8::10", 0, 3600),
		rr("ftp", "ALIAS", "www.example.com.", 0, 3600),
		rr("", "CAA", `0 issue "letsencrypt.org"`, 0, 3600),
		rr("mail", "CNAME", "www.example.com.", 0, 3600),
		rr("legacy", "DNAME", "example.net.", 0, 3600),
		rr("sub", "DS", "12345 13 2 49FD46E6C4B45C55D4AC69CBD3CD34AC1AFE51DE", 0, 3600),
		rr("host", "HINFO", `"Intel" "Linux"`, 0, 3600),
		rr("", "LOC", "52 22 23.000 N 4 53 32.000 E -2.00m 0.00m 10000m 10m", 0, 3600),
		rr("", "MX", "mail.example.com.", 10, 3600),
		rr("", "NAPTR", `100 "s" "SIP+D2U" "" _sip._udp.example.com.`, 10, 3600),
		rr("10.2.0.192.in-addr.arpa.", "PTR", "www.example.com.", 0, 3600),
		rr("", "RP", "admin.example.com. txt.example.com.", 0, 3600),
		rr("_sip._tcp", "SRV", "0 5060 sip.example.com.", 10, 3600),
		rr("host", "SSHFP", "2 1 123456789ABCDEF67890123456789ABCDEF67890", 0, 3600),
		rr("_443._tcp.www", "TLSA", "3 1 1 0D6FCE3E9B0B7CDBDF9C7BD0E7A5B3A1B0E1C2D3E4F5061728394A5B6C7D8E9F", 0, 3600),
		rr("", "TXT", "v=spf1 mx a -all", 0, 3600),
	}
	out, err := RenderZone(goldenSoa(), records, true, "")
	require.NoError(t, err)
	checkGolden(t, "zone_all_types", out)
}

// TestGoldenZoneTxtSplit: a 600-byte TXT record splits into 255/255/90
// chunks joined with `" "`.
func TestGoldenZoneTxtSplit(t *testing.T) {
	dkim := "v=DKIM1; k=rsa; p=" + strings.Repeat("A", 582)
	records := []map[string]any{
		rr("", "NS", "ns1.example.com.", 0, 3600),
		rr("mail._domainkey", "TXT", dkim, 0, 3600),
	}
	out, err := RenderZone(goldenSoa(), records, true, "")
	require.NoError(t, err)
	checkGolden(t, "zone_txt_split", out)
}

// TestGoldenZoneCAALegacy: BIND < 9.9.6 renders CAA as TYPE257 hex; the
// real issue record suppresses the synthetic one.
func TestGoldenZoneCAALegacy(t *testing.T) {
	records := []map[string]any{
		rr("", "NS", "ns1.example.com.", 0, 3600),
		rr("", "CAA", `0 issuewild "letsencrypt.org"`, 0, 3600),
		rr("", "CAA", `0 issue "letsencrypt.org"`, 0, 3600),
	}
	out, err := RenderZone(goldenSoa(), records, false, "")
	require.NoError(t, err)
	checkGolden(t, "zone_caa_legacy", out)
}

// TestGoldenZoneCAAIssuewildOnly: an issuewild-only set on legacy BIND
// gets the synthetic TYPE257 `issue ";"` record appended.
func TestGoldenZoneCAAIssuewildOnly(t *testing.T) {
	records := []map[string]any{
		rr("", "NS", "ns1.example.com.", 0, 3600),
		rr("", "CAA", `0 issuewild "letsencrypt.org"`, 0, 3600),
	}
	out, err := RenderZone(goldenSoa(), records, false, "")
	require.NoError(t, err)
	checkGolden(t, "zone_caa_issuewild_only", out)
}
