package api

// Server Config form metadata (spec server-config-sync, UI half): the tab and
// field shape of the per-server INI editor, generated from the legacy
// interface/web/admin/form/server_config.tform.php plus en_server_config.lng
// and narrowed to the keys internal/getconf actually decodes.
//
// A legacy field with no consumer in the Go daemon is deliberately absent —
// rendering a knob the applying plugins never read would let an operator set
// a value that silently does nothing. docs/server-config-module.md lists the
// omissions per section and why.
//
// One tab per INI section, so the SPA can PUT /api/servers/:id/config/:section
// tab by tab.

// serverConfigForm is the FormMeta served by GET /api/servers/config/meta.
func serverConfigForm() FormMeta {
	return FormMeta{
		Name:  "server_config",
		Title: "srvcfg.title",
		Tabs: []FormTabMeta{
			{
				Name:  "web",
				Label: "srvcfg.tab.web",
				Fields: []FormFieldMeta{
					{Name: "server_type", Label: "srvcfg.web.server_type", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "apache", Options: []Option{{Value: "apache", Label: "Apache"}, {Value: "nginx", Label: "Nginx"}}},
					{Name: "website_basedir", Label: "srvcfg.web.website_basedir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "website_path", Label: "srvcfg.web.website_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "website_symlinks", Label: "srvcfg.web.website_symlinks", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "website_symlinks_rel", Label: "srvcfg.web.website_symlinks_rel", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "network_filesystem", Label: "srvcfg.web.network_filesystem", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "vhost_rewrite_v6", Label: "srvcfg.web.vhost_rewrite_v6", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "vhost_conf_dir", Label: "srvcfg.web.vhost_conf_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "vhost_conf_enabled_dir", Label: "srvcfg.web.vhost_conf_enabled_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "apache_init_script", Label: "srvcfg.web.apache_init_script", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "nginx_vhost_conf_dir", Label: "srvcfg.web.nginx_vhost_conf_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "nginx_vhost_conf_enabled_dir", Label: "srvcfg.web.nginx_vhost_conf_enabled_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "security_level", Label: "srvcfg.web.security_level", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "20", Options: []Option{{Value: "10", Label: "Medium"}, {Value: "20", Label: "High"}}},
					{Name: "user", Label: "srvcfg.web.user", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "group", Label: "srvcfg.web.group", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "nginx_user", Label: "srvcfg.web.nginx_user", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "nginx_group", Label: "srvcfg.web.nginx_group", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "apps_vhost_enabled", Label: "srvcfg.web.apps_vhost_enabled", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y"},
					{Name: "apps_vhost_port", Label: "srvcfg.web.apps_vhost_port", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "8081"},
					{Name: "apps_vhost_ip", Label: "srvcfg.web.apps_vhost_ip", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "_default_"},
					{Name: "apps_vhost_servername", Label: "srvcfg.web.apps_vhost_servername", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_open_basedir", Label: "srvcfg.web.php_open_basedir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "htaccess_allow_override", Label: "srvcfg.web.htaccess_allow_override", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "awstats_conf_dir", Label: "srvcfg.web.awstats_conf_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "awstats_data_dir", Label: "srvcfg.web.awstats_data_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "awstats_pl", Label: "srvcfg.web.awstats_pl", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "awstats_buildstaticpages_pl", Label: "srvcfg.web.awstats_buildstaticpages_pl", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_ini_path_apache", Label: "srvcfg.web.php_ini_path_apache", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_ini_path_cgi", Label: "srvcfg.web.php_ini_path_cgi", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "check_apache_config", Label: "srvcfg.web.check_apache_config", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "enable_sni", Label: "srvcfg.web.enable_sni", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "skip_le_check", Label: "srvcfg.web.skip_le_check", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n"},
					{Name: "enable_ip_wildcard", Label: "srvcfg.web.enable_ip_wildcard", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overtraffic_notify_admin", Label: "srvcfg.web.overtraffic_notify_admin", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overtraffic_notify_reseller", Label: "srvcfg.web.overtraffic_notify_reseller", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overtraffic_notify_client", Label: "srvcfg.web.overtraffic_notify_client", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "nginx_cgi_socket", Label: "srvcfg.web.nginx_cgi_socket", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_fpm_init_script", Label: "srvcfg.web.php_fpm_init_script", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_fpm_ini_path", Label: "srvcfg.web.php_fpm_ini_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_fpm_pool_dir", Label: "srvcfg.web.php_fpm_pool_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_fpm_start_port", Label: "srvcfg.web.php_fpm_start_port", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_fpm_socket_dir", Label: "srvcfg.web.php_fpm_socket_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "php_default_hide", Label: "srvcfg.web.php_default_hide", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "php_default_name", Label: "srvcfg.web.php_default_name", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "Default"},
					{Name: "set_folder_permissions_on_update", Label: "srvcfg.web.set_folder_permissions_on_update", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "add_web_users_to_sshusers_group", Label: "srvcfg.web.add_web_users_to_sshusers_group", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "connect_userid_to_webid", Label: "srvcfg.web.connect_userid_to_webid", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "connect_userid_to_webid_start", Label: "srvcfg.web.connect_userid_to_webid_start", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "10000"},
					{Name: "web_folder_protection", Label: "srvcfg.web.web_folder_protection", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "web_folder_permission", Label: "srvcfg.web.web_folder_permission", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "0710", Options: []Option{{Value: "0710", Label: "0710"}, {Value: "0711", Label: "0711"}, {Value: "0750", Label: "0750"}, {Value: "0751", Label: "0751"}}},
					{Name: "php_ini_check_minutes", Label: "srvcfg.web.php_ini_check_minutes", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "1"},
					{Name: "overtraffic_disable_web", Label: "srvcfg.web.overtraffic_disable_web", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_notify_threshold", Label: "srvcfg.web.overquota_notify_threshold", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "90"},
					{Name: "overquota_notify_admin", Label: "srvcfg.web.overquota_notify_admin", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_notify_reseller", Label: "srvcfg.web.overquota_notify_reseller", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_notify_client", Label: "srvcfg.web.overquota_notify_client", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_notify_freq", Label: "srvcfg.web.overquota_notify_freq", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "7"},
					{Name: "overquota_db_notify_threshold", Label: "srvcfg.web.overquota_db_notify_threshold", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "90"},
					{Name: "overquota_db_notify_admin", Label: "srvcfg.web.overquota_db_notify_admin", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_db_notify_reseller", Label: "srvcfg.web.overquota_db_notify_reseller", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_db_notify_client", Label: "srvcfg.web.overquota_db_notify_client", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "overquota_notify_onok", Label: "srvcfg.web.overquota_notify_onok", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "logging", Label: "srvcfg.web.logging", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "yes", Options: []Option{{Value: "yes", Label: "Yes"}, {Value: "anon", Label: "Anonymize IP"}, {Value: "no", Label: "No"}}},
					{Name: "php_fpm_reload_mode", Label: "srvcfg.web.php_fpm_reload_mode", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "reload", Options: []Option{{Value: "reload", Label: "Reload"}, {Value: "restart", Label: "Restart"}}},
					{Name: "php_fpm_default_chroot", Label: "srvcfg.web.php_fpm_default_chroot", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "vhost_proxy_protocol_enabled", Label: "srvcfg.web.vhost_proxy_protocol_enabled", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "n", Options: []Option{{Value: "n", Label: "Disabled"}, {Value: "y", Label: "Enabled (per site)"}, {Value: "all", Label: "Enabled (all sites)"}}},
					{Name: "vhost_proxy_protocol_protocols", Label: "srvcfg.web.vhost_proxy_protocol_protocols", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "vhost_proxy_protocol_http_port", Label: "srvcfg.web.vhost_proxy_protocol_http_port", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "880"},
					{Name: "vhost_proxy_protocol_https_port", Label: "srvcfg.web.vhost_proxy_protocol_https_port", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "8443"},
					{Name: "le_signature_type", Label: "srvcfg.web.le_signature_type", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "ECDSA", Options: []Option{{Value: "RSA", Label: "RSA (RSA encryption with SHA-256)"}, {Value: "ECDSA", Label: "ECDSA (Elliptic Curve Digital Signature Algorithm)"}}},
					{Name: "le_delete_on_site_remove", Label: "srvcfg.web.le_delete_on_site_remove", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "le_auto_cleanup", Label: "srvcfg.web.le_auto_cleanup", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "le_revoke_before_delete", Label: "srvcfg.web.le_revoke_before_delete", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "y", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "le_auto_cleanup_denylist", Label: "srvcfg.web.le_auto_cleanup_denylist", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "[server_name]"},
				},
			},
			{
				Name:  "dns",
				Label: "srvcfg.tab.dns",
				Fields: []FormFieldMeta{
					{Name: "bind_user", Label: "srvcfg.dns.bind_user", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "bind_group", Label: "srvcfg.dns.bind_group", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "bind_zonefiles_dir", Label: "srvcfg.dns.bind_zonefiles_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "bind_keyfiles_dir", Label: "srvcfg.dns.bind_keyfiles_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "bind_zonefiles_masterprefix", Label: "srvcfg.dns.bind_zonefiles_masterprefix", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "bind_zonefiles_slaveprefix", Label: "srvcfg.dns.bind_zonefiles_slaveprefix", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "named_conf_path", Label: "srvcfg.dns.named_conf_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "named_conf_local_path", Label: "srvcfg.dns.named_conf_local_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "disable_bind_log", Label: "srvcfg.dns.disable_bind_log", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "dnssec_resign_days", Label: "srvcfg.dns.dnssec_resign_days", Type: "text", Datatype: "INTEGER", Formtype: "TEXT"},
					{Name: "dns_backend", Label: "srvcfg.dns.dns_backend", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "bind", Options: []Option{{Value: "bind", Label: "BIND"}, {Value: "powerdns", Label: "PowerDNS"}}},
					{Name: "powerdns_axfr_conf", Label: "srvcfg.dns.powerdns_axfr_conf", Type: "textarea", Datatype: "VARCHAR", Formtype: "TEXTAREA"},
				},
			},
			{
				Name:  "mail",
				Label: "srvcfg.tab.mail",
				Fields: []FormFieldMeta{
					{Name: "module", Label: "srvcfg.mail.module", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Options: []Option{{Value: "postfix_mysql", Label: "postfix_mysql"}}},
					{Name: "maildir_path", Label: "srvcfg.mail.maildir_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "/home/vmail/[domain]/[localpart]/"},
					{Name: "homedir_path", Label: "srvcfg.mail.homedir_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "/home/vmail/"},
					{Name: "maildir_format", Label: "srvcfg.mail.maildir_format", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "maildir", Options: []Option{{Value: "maildir", Label: "Maildir"}, {Value: "mdbox", Label: "mdbox"}}},
					{Name: "dkim_path", Label: "srvcfg.mail.dkim_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "/var/lib/amavis/dkim"},
					{Name: "dkim_strength", Label: "srvcfg.mail.dkim_strength", Type: "select", Datatype: "INTEGER", Formtype: "SELECT", Default: "2048", Options: []Option{{Value: "1024", Label: "weak (1024)"}, {Value: "2048", Label: "normal (2048)"}, {Value: "4096", Label: "strong (4096)"}}},
					{Name: "content_filter", Label: "srvcfg.mail.content_filter", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "rspamd", Options: []Option{{Value: "amavisd", Label: "Amavisd"}, {Value: "rspamd", Label: "Rspamd"}}},
					{Name: "rspamd_password", Label: "srvcfg.mail.rspamd_password", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "rspamd_url", Label: "srvcfg.mail.rspamd_url", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "rspamd_redis_servers", Label: "srvcfg.mail.rspamd_redis_servers", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "127.0.0.1"},
					{Name: "rspamd_redis_passwd", Label: "srvcfg.mail.rspamd_redis_passwd", Type: "password", Datatype: "VARCHAR", Formtype: "PASSWORD"},
					{Name: "rspamd_redis_bayes_servers", Label: "srvcfg.mail.rspamd_redis_bayes_servers", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "127.0.0.1"},
					{Name: "rspamd_redis_bayes_passwd", Label: "srvcfg.mail.rspamd_redis_bayes_passwd", Type: "password", Datatype: "VARCHAR", Formtype: "PASSWORD"},
					{Name: "rspamd_spam_tag_level", Label: "srvcfg.mail.rspamd_spam_tag_level", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "rspamd_spam_kill_level", Label: "srvcfg.mail.rspamd_spam_kill_level", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "rspamd_greylisting_level", Label: "srvcfg.mail.rspamd_greylisting_level", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "pop3_imap_daemon", Label: "srvcfg.mail.pop3_imap_daemon", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "dovecot", Options: []Option{{Value: "courier", Label: "Courier"}, {Value: "dovecot", Label: "Dovecot"}}},
					{Name: "mail_filter_syntax", Label: "srvcfg.mail.mail_filter_syntax", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "sieve", Options: []Option{{Value: "maildrop", Label: "Maildrop"}, {Value: "sieve", Label: "Sieve"}}},
					{Name: "mailuser_uid", Label: "srvcfg.mail.mailuser_uid", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "5000"},
					{Name: "mailuser_gid", Label: "srvcfg.mail.mailuser_gid", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "5000"},
					{Name: "mailuser_name", Label: "srvcfg.mail.mailuser_name", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "vmail"},
					{Name: "mailuser_group", Label: "srvcfg.mail.mailuser_group", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT", Default: "vmail"},
					{Name: "mailbox_virtual_uidgid_maps", Label: "srvcfg.mail.mailbox_virtual_uidgid_maps", Type: "checkbox", Datatype: "VARCHAR", Formtype: "CHECKBOX", Default: "n", Options: []Option{{Value: "n", Label: "n"}, {Value: "y", Label: "y"}}},
					{Name: "relayhost", Label: "srvcfg.mail.relayhost", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "relayhost_user", Label: "srvcfg.mail.relayhost_user", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "relayhost_password", Label: "srvcfg.mail.relayhost_password", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "mailbox_size_limit", Label: "srvcfg.mail.mailbox_size_limit", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "0"},
					{Name: "message_size_limit", Label: "srvcfg.mail.message_size_limit", Type: "text", Datatype: "INTEGER", Formtype: "TEXT", Default: "0"},
					{Name: "mailbox_soft_delete", Label: "srvcfg.mail.mailbox_soft_delete", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "0", Options: []Option{{Value: "0", Label: "soft_delete_directly_txt"}, {Value: "-1", Label: "soft_delete_keep_indefinitely_txt"}, {Value: "1", Label: "soft_delete_keep_1_txt"}, {Value: "7", Label: "soft_delete_keep_7_txt"}, {Value: "30", Label: "soft_delete_keep_30_txt"}, {Value: "90", Label: "soft_delete_keep_90_txt"}, {Value: "365", Label: "soft_delete_keep_365_txt"}}},
					{Name: "sendmail_path", Label: "srvcfg.mail.sendmail_path", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
				},
			},
			{
				Name:  "getmail",
				Label: "srvcfg.tab.getmail",
				Fields: []FormFieldMeta{
					{Name: "getmail_config_dir", Label: "srvcfg.getmail.getmail_config_dir", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "getmail_program", Label: "srvcfg.getmail.getmail_program", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "getmail_user", Label: "srvcfg.getmail.getmail_user", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
				},
			},
			{
				Name:  "jailkit",
				Label: "srvcfg.tab.jailkit",
				Fields: []FormFieldMeta{
					{Name: "jailkit_chroot_home", Label: "srvcfg.jailkit.jailkit_chroot_home", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "jailkit_chroot_app_sections", Label: "srvcfg.jailkit.jailkit_chroot_app_sections", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "jailkit_chroot_app_programs", Label: "srvcfg.jailkit.jailkit_chroot_app_programs", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "jailkit_chroot_cron_programs", Label: "srvcfg.jailkit.jailkit_chroot_cron_programs", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "jailkit_chroot_authorized_keys_template", Label: "srvcfg.jailkit.jailkit_chroot_authorized_keys_template", Type: "text", Datatype: "VARCHAR", Formtype: "TEXT"},
					{Name: "jailkit_hardlinks", Label: "srvcfg.jailkit.jailkit_hardlinks", Type: "select", Datatype: "VARCHAR", Formtype: "SELECT", Default: "allow", Options: []Option{{Value: "allow", Label: "jailkit_hardlinks_allow_txt"}, {Value: "no", Label: "jailkit_hardlinks_no_txt"}, {Value: "yes", Label: "jailkit_hardlinks_yes_txt"}}},
				},
			},
		},
	}
}
