package installer

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

// PanelUser is the unprivileged system user the serve unit runs as
// (init/systemd/go-ispconfig-serve.service: User=go-ispconfig).
const PanelUser = "go-ispconfig"

// userStep creates the go-ispconfig system user consumed by the serve unit
// and the config/ssl file ownership.
type userStep struct{}

// Name identifies the step in the pipeline log.
func (userStep) Name() string { return "panel-user" }

// Run creates the system user and the sshusers group when absent.
func (userStep) Run(ctx context.Context, st *State) error {
	// The web module adds site shell users to the sshusers group
	// (server_config add_web_users_to_sshusers_group=y); the PHP installer
	// creates it unconditionally (installer_base groupadd sshusers).
	if _, err := st.Exec.Run(ctx, nil, "getent", "group", "sshusers"); err != nil {
		if _, err := st.Exec.Run(ctx, nil, "groupadd", "sshusers"); err != nil {
			return fmt.Errorf("creating group sshusers: %w", err)
		}
	}
	if _, err := st.Exec.Run(ctx, nil, "id", "-u", PanelUser); err == nil {
		return Skip("user " + PanelUser + " exists")
	}
	if _, err := st.Exec.Run(ctx, nil, "useradd", "--system", "--user-group",
		"--home-dir", st.ConfigDir, "--no-create-home",
		"--shell", "/usr/sbin/nologin", PanelUser); err != nil {
		return fmt.Errorf("creating user %s: %w", PanelUser, err)
	}
	return nil
}

// configTomlStep writes <ConfigDir>/config.toml with the DSN of the
// generated (or reused) DB credentials and the panel listen settings.
// tls_cert/tls_key stay empty on purpose: serve then manages the
// self-signed pair under <ConfigDir>/ssl/ itself (foundation D13), which
// the tls-cert step pre-seeds. Group-readable by the panel user; backed up
// only when content differs.
type configTomlStep struct{}

// Name identifies the step in the pipeline log.
func (configTomlStep) Name() string { return "config-toml" }

// Run renders and writes the config, reusing credentials on re-run (the
// mariadb step resolved st.DBPassword from any existing config first).
func (configTomlStep) Run(ctx context.Context, st *State) error {
	path := filepath.Join(st.ConfigDir, "config.toml")

	// The JWT signing key is generated once and then reused: regenerating it
	// on every `install --update` would invalidate every outstanding JWT and
	// make the file differ on each run, defeating the unchanged check.
	jwtSecret, err := reuseOrGenerateJWTSecret(path)
	if err != nil {
		return err
	}

	content := fmt.Sprintf(`# Generated by go-ispconfig install. Unlisted keys use built-in defaults.

[server]
host = "0.0.0.0"
port = %d
https = true

[database]
dsn = %q

[queue]
addr = "localhost:6379"

[auth]
# Signs the short-lived JWTs an API token can be exchanged for
# (POST /api/tokens/exchange). Replacing it invalidates every outstanding JWT.
jwt_secret = %q
jwt_ttl = "15m"
`, st.Answers.PanelPort, st.ispconfigDSN(), jwtSecret)

	changed, _, err := writeFileBackup(path, []byte(content), 0o640)
	if err != nil {
		return err
	}
	// root:go-ispconfig — the config holds DB credentials; the panel user
	// reads it, nobody else.
	if _, err := st.Exec.Run(ctx, nil, "chown", "root:"+PanelUser, path); err != nil {
		return fmt.Errorf("chown %s: %w", path, err)
	}
	if !changed {
		return Skip("config.toml unchanged")
	}
	return nil
}

// jwtSecretRe finds an existing signing key in a config.toml so a re-run
// keeps it. The key is matched loosely (any quoting whitespace) because the
// operator may have edited the file by hand.
var jwtSecretRe = regexp.MustCompile(`(?m)^\s*jwt_secret\s*=\s*"([^"]*)"`)

// reuseOrGenerateJWTSecret returns the key already stored at path, or a fresh
// 32-byte random one when the file has none (or does not exist yet).
func reuseOrGenerateJWTSecret(path string) (string, error) {
	if existing, err := os.ReadFile(path); err == nil {
		if m := jwtSecretRe.FindSubmatch(existing); len(m) == 2 && len(m[1]) > 0 {
			return string(m[1]), nil
		}
	}
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generating jwt secret: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
