package installer

import (
	"context"
	"fmt"
	"path/filepath"
)

// PanelUser is the unprivileged system user the serve unit runs as
// (init/systemd/go-ispconfig-serve.service: User=go-ispconfig).
const PanelUser = "go-ispconfig"

// userStep creates the go-ispconfig system user consumed by the serve unit
// and the config/ssl file ownership.
type userStep struct{}

// Name identifies the step in the pipeline log.
func (userStep) Name() string { return "panel-user" }

// Run creates the system user when absent.
func (userStep) Run(ctx context.Context, st *State) error {
	if _, err := st.Exec.Run(ctx, nil, "id", "-u", PanelUser); err == nil {
		return Skip("user " + PanelUser + " exists")
	}
	if _, err := st.Exec.Run(ctx, nil, "useradd", "--system", "--user-group",
		"--home-dir", st.ConfigDir, "--no-create-home",
		"--shell", "/usr/sbin/nologin", PanelUser); err != nil {
		return fmt.Errorf("creating user %s: %w", PanelUser, err)
	}
	return nil
}

// configTomlStep writes <ConfigDir>/config.toml with the DSN of the
// generated (or reused) DB credentials and the panel listen settings.
// tls_cert/tls_key stay empty on purpose: serve then manages the
// self-signed pair under <ConfigDir>/ssl/ itself (foundation D13), which
// the tls-cert step pre-seeds. Group-readable by the panel user; backed up
// only when content differs.
type configTomlStep struct{}

// Name identifies the step in the pipeline log.
func (configTomlStep) Name() string { return "config-toml" }

// Run renders and writes the config, reusing credentials on re-run (the
// mariadb step resolved st.DBPassword from any existing config first).
func (configTomlStep) Run(ctx context.Context, st *State) error {
	content := fmt.Sprintf(`# Generated by go-ispconfig install. Unlisted keys use built-in defaults.

[server]
host = "0.0.0.0"
port = %d
https = true

[database]
dsn = %q

[queue]
addr = "localhost:6379"
`, st.Answers.PanelPort, st.ispconfigDSN())

	path := filepath.Join(st.ConfigDir, "config.toml")
	changed, _, err := writeFileBackup(path, []byte(content), 0o640)
	if err != nil {
		return err
	}
	// root:go-ispconfig — the config holds DB credentials; the panel user
	// reads it, nobody else.
	if _, err := st.Exec.Run(ctx, nil, "chown", "root:"+PanelUser, path); err != nil {
		return fmt.Errorf("chown %s: %w", path, err)
	}
	if !changed {
		return Skip("config.toml unchanged")
	}
	return nil
}
