package mastertpl

// Golden-file tests: every bundled .master template is rendered with a
// realistic fixture (variable names taken from the template itself and
// from the PHP plugins that feed it: nginx_plugin.inc.php and
// bind_plugin.inc.php) and compared byte-for-byte against
// golden/<name>.golden. Any engine change that alters rendered output
// fails these tests with a diff.
//
// The golden files were generated by this engine and verified line by
// line against the semantics of the PHP engine
// (base/ispconfig3_install/server/lib/classes/tpl.inc.php with the
// vlibIni options GLOBAL_VARS=1, SET_LOOP_VAR=1, CASELESS=0,
// UNKNOWNS=ignore, DEFAULT_ESCAPE=none); php-cli was not available in
// the build environment to run vlibTemplate directly. To regenerate
// after an INTENDED engine or fixture change:
//
//	go test ./internal/mastertpl -run TestGolden -update
//
// and review the diff. If php-cli is available, cross-check by loading
// tpl.inc.php, calling setVar/setLoop with the same fixture data and
// diffing grab() output against the golden file.

import (
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

var update = flag.Bool("update", false, "rewrite golden files with current render output")

func renderBundled(t *testing.T, name string, vars map[string]any, loops map[string][]map[string]any) string {
	t.Helper()
	src, err := Templates.ReadFile("templates/" + name)
	require.NoError(t, err)
	tpl := New(string(src))
	for k, v := range vars {
		tpl.SetVar(k, v)
	}
	for k, v := range loops {
		tpl.SetLoop(k, v)
	}
	out, err := tpl.Render()
	require.NoError(t, err)
	return out
}

func checkGolden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("golden", name+".golden")
	if *update {
		require.NoError(t, os.MkdirAll("golden", 0o755))
		require.NoError(t, os.WriteFile(path, []byte(got), 0o644))
		return
	}
	want, err := os.ReadFile(path)
	require.NoError(t, err, "missing golden file; run: go test ./internal/mastertpl -run TestGolden -update")
	require.Equal(t, string(want), got, "rendered %s differs from golden file %s", name, path)
}

func TestGoldenBindNamedConfLocal(t *testing.T) {
	// Fixture mirrors bind_plugin.inc.php write_named_conf(): one row
	// per active dns_soa zone; options is a pre-rendered multi-line
	// block ending in "\n" (or empty).
	got := renderBundled(t, "bind_named.conf.local.master", nil, map[string][]map[string]any{
		"zones": {
			{
				"zone":          "example.com",
				"zonefile_path": "/etc/bind/pri.example.com",
				"options":       "        allow-transfer {192.168.10.6;};\n        also-notify {192.168.10.6;};\n",
			},
			{
				"zone":          "example.org",
				"zonefile_path": "/etc/bind/pri.example.org.signed",
				"options":       "",
			},
		},
	})
	checkGolden(t, "bind_named.conf.local", got)
}

func TestGoldenBindNamedConfLocalSlave(t *testing.T) {
	// Fixture mirrors the dns_slave branch of write_named_conf().
	got := renderBundled(t, "bind_named.conf.local.slave", nil, map[string][]map[string]any{
		"zones": {
			{
				"zone":          "customer.net",
				"zonefile_path": "/etc/bind/slave/sec.customer.net",
				"options":       "        masters {192.168.10.20;};\n        allow-transfer {none;};\n",
			},
		},
	})
	checkGolden(t, "bind_named.conf.local.slave", got)
}

func TestGoldenBindPriDomain(t *testing.T) {
	// Globals mirror $tpl->setVar($zone) with a dns_soa row; the
	// "zones" loop mirrors the dns_rr rows after the plugin's
	// pre-processing (ttl 0 -> "", empty name -> "@").
	vars := map[string]any{
		"ttl":     3600,
		"ns":      "ns1.example.com.",
		"mbox":    "admin.example.com.",
		"serial":  2026080101,
		"refresh": 7200,
		"retry":   540,
		"expire":  604800,
		"minimum": 3600,
	}
	loops := map[string][]map[string]any{
		"zones": {
			{"name": "example.com.", "type": "NS", "data": "ns1.example.com.", "aux": 0, "ttl": 3600},
			{"name": "example.com.", "type": "NS", "data": "ns2.example.com.", "aux": 0, "ttl": 3600},
			{"name": "example.com.", "type": "A", "data": "192.168.10.5", "aux": 0, "ttl": 3600},
			{"name": "www", "type": "A", "data": "192.168.10.5", "aux": 0, "ttl": ""},
			{"name": "example.com.", "type": "AAAA", "data": "2001:db8::5", "aux": 0, "ttl": 3600},
			{"name": "example.com.", "type": "MX", "data": "mail.example.com.", "aux": 10, "ttl": 3600},
			{"name": "mail", "type": "CNAME", "data": "example.com.", "aux": 0, "ttl": 3600},
			{"name": "example.com.", "type": "TXT", "data": "v=spf1 mx a -all", "aux": 0, "ttl": 3600},
			{"name": "_sip._tcp", "type": "SRV", "data": "0 5060 sip.example.com.", "aux": 10, "ttl": 3600},
			{"name": "example.com.", "type": "CAA", "data": "0 issue \"letsencrypt.org\"", "aux": 0, "ttl": 3600},
		},
	}
	got := renderBundled(t, "bind_pri.domain.master", vars, loops)
	checkGolden(t, "bind_pri.domain", got)
}

func TestGoldenPhpFpmPool(t *testing.T) {
	// Fixture mirrors nginx_plugin.inc.php php_fpm_pool_update() for a
	// default Debian-ish site: unix socket, dynamic pm, security level
	// 20, open_basedir enabled, no chroot, two custom php.ini settings.
	vars := map[string]any{
		"fpm_pool":                 "web1",
		"use_tcp":                  0,
		"use_socket":               1,
		"fpm_port":                 9010,
		"fpm_socket":               "/var/lib/php7.4-fpm/web1.sock",
		"fpm_listen_mode":          "0660",
		"fpm_listen_user":          "web1",
		"fpm_listen_group":         "www-data",
		"fpm_user":                 "web1",
		"fpm_group":                "client1",
		"fpm_domain":               "example.com",
		"domain":                   "example.com",
		"pm":                       "dynamic",
		"pm_max_children":          10,
		"pm_start_servers":         2,
		"pm_min_spare_servers":     1,
		"pm_max_spare_servers":     5,
		"pm_process_idle_timeout":  10,
		"pm_max_requests":          0,
		"document_root":            "/var/www/clients/client1/web1",
		"security_level":           "20",
		"php_open_basedir":         "/var/www/clients/client1/web1/web:/var/www/clients/client1/web1/private:/var/www/clients/client1/web1/tmp:/usr/share/php:/tmp",
		"enable_php_open_basedir":  "",
		"custom_session_save_path": "n",
		"custom_sendmail_path":     "n",
		// php_fpm_chroot is only set by the plugin when chroot is 'y'.
	}
	loops := map[string][]map[string]any{
		"custom_php_ini_settings": {
			{"ini_setting": "php_admin_value[memory_limit] = 256M"},
			{"ini_setting": "php_admin_flag[display_errors] = off"},
		},
	}
	got := renderBundled(t, "php_fpm_pool.conf.master", vars, loops)
	checkGolden(t, "php_fpm_pool.conf", got)
}

func TestGoldenNginxVhost(t *testing.T) {
	// Fixture mirrors nginx_plugin.inc.php update() for an SSL-enabled
	// PHP-FPM site (unix socket, modern nginx with `http2 on;`), with
	// alias SEO redirects, a rewrite and a proxy own_redirect (nested
	// proxy_directives), custom rewrite rules and nginx directives, a
	// protected folder, and one aliasdomain redirect server block with
	// its own nested alias_seo_redirects2.
	vars := map[string]any{
		"ip_address":                   "192.168.10.5",
		"http_port":                    "80",
		"https_port":                   "443",
		"use_proxy_protocol":           "n",
		"ipv6_enabled":                 "",
		"ipv6_wildcard":                0,
		"ssl_enabled":                  "y",
		"tls13_supported":              "y",
		"http2_directive_compat_quirk": "",
		"nginx_full_version":           "1.26.1",
		"ssl_crt_file":                 "/var/www/clients/client1/web1/ssl/example.com.crt",
		"ssl_key_file":                 "/var/www/clients/client1/web1/ssl/example.com.key",
		"domain":                       "example.com",
		"alias":                        "www.example.com",
		"web_document_root_www":        "/var/www/example.com/web",
		"web_document_root_www_proxy":  "root /var/www/example.com/web;",
		"disable_symlinknotowner":      "n",
		"rewrite_to_https":             "y",
		"seo_redirect_enabled":         0,
		"errordocs":                    1,
		"logging":                      "yes",
		"stats_auth_passwd_file":       "/var/www/clients/client1/web1/web/stats/.htpasswd_stats",
		"rnd_php_dummy_file":           "/9f86d081884c7d659a2feaa0c55ad015.htm",
		"php":                          "php-fpm",
		"use_tcp":                      0,
		"use_socket":                   1,
		"fpm_port":                     9010,
		"fpm_socket":                   "/var/lib/php7.4-fpm/web1.sock",
		"php_fpm_chroot":               "n",
		"php_fpm_chroot_web_folder":    "/web",
		"cgi":                          "n",
		"document_root":                "/var/www/clients/client1/web1",
		"ssi":                          "n",
		"enable_pagespeed":             "n",
	}
	loops := map[string][]map[string]any{
		"alias_seo_redirects": {
			{
				"alias_seo_redirect_operator":      "=",
				"alias_seo_redirect_origin_domain": "alias.example.com",
				"alias_seo_redirect_target_domain": "www.alias.example.com",
			},
		},
		"own_redirects": {
			{
				"use_rewrite":          true,
				"use_proxy":            false,
				"rewrite_exclude":      `(?!/(stats|error|\.well-known/acme-challenge))/`,
				"rewrite_target":       "/app",
				"rewrite_type":         "last",
				"exclude_own_hostname": "",
				"proxy_directives":     false,
			},
			{
				"use_rewrite":    false,
				"use_proxy":      true,
				"rewrite_target": "http://127.0.0.1:8081",
				"rewrite_subdir": "",
				"proxy_directives": []map[string]any{
					{"proxy_directive": "proxy_set_header Host $host;"},
					{"proxy_directive": "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"},
				},
			},
		},
		"rewrite_rules": {
			{"rewrite_rule": "rewrite ^/old-page$ /new-page permanent;"},
		},
		"nginx_directives": {
			{"nginx_directive": "client_max_body_size 100M;"},
			{"nginx_directive": "fastcgi_read_timeout 300;"},
		},
		"basic_auth_locations": {
			{
				"htpasswd_location": "/admin",
				"htpasswd_path":     "/var/www/clients/client1/web1/web/admin/",
			},
		},
		"redirects": {
			{
				"rewrite_domain": "old-domain.com",
				// The plugin builds these rows with boolean flags
				// ('n' would be truthy in PHP, so realism matters).
				"use_rewrite":      true,
				"use_proxy":        false,
				"proxy_directives": false,
				"rewrite_target":   "https://example.com",
				"rewrite_type":     "permanent",
				"alias_seo_redirects2": []map[string]any{
					{
						"alias_seo_redirect_operator":      "=",
						"alias_seo_redirect_origin_domain": "old-domain.com",
						"alias_seo_redirect_target_domain": "www.old-domain.com",
					},
				},
			},
		},
	}
	got := renderBundled(t, "nginx_vhost.conf.master", vars, loops)
	checkGolden(t, "nginx_vhost.conf", got)
}
