package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v5"
	"gorm.io/gorm"

	"go-ispconfig/internal/model"
)

const (
	// SessionCookieName is the HTTP-only cookie carrying the session id for
	// browser (SPA) clients.
	SessionCookieName = "goisp_session"
	// CSRFHeaderName is the request header that must carry the per-session
	// CSRF token on every mutating request authenticated via cookie.
	CSRFHeaderName = "X-CSRF-Token"
	// DefaultSessionTTL is the idle expiration applied when NewStore is
	// given a non-positive TTL.
	DefaultSessionTTL = time.Hour
	// PermanentSessionTTL is the idle expiration of "stay logged in"
	// sessions (sys_session.permanent = 'y'): long-lived, never infinite.
	PermanentSessionTTL = 30 * 24 * time.Hour
)

// ErrSessionNotFound is returned by Store.Get for unknown or expired
// session ids.
var ErrSessionNotFound = errors.New("auth: session not found")

// SessionData is the authenticated state stored as JSON in
// sys_session.session_data and attached to the request context.
type SessionData struct {
	// UserID is sys_user.userid; user id 1 is the superadmin.
	UserID uint32 `json:"user_id"`
	// Username is sys_user.username.
	Username string `json:"username"`
	// Typ is the sys_user.typ access level ("admin" or "user").
	Typ string `json:"typ"`
	// Groups is the effective sys_group id list of the user, including a
	// reseller's client groups (resolved at login, design D4).
	Groups []uint32 `json:"groups"`
	// DefaultGroup is sys_user.default_group, stamped onto records the
	// user inserts.
	DefaultGroup uint32 `json:"default_group"`
	// Language is the panel language of the user.
	Language string `json:"language"`
	// Modules is the sys_user.modules CSV (panel module visibility).
	Modules string `json:"modules,omitempty"`
	// CSRFToken is the per-session token required on mutating cookie
	// requests. It is generated by Store.Create.
	CSRFToken string `json:"csrf_token"`
	// Permanent marks a "stay logged in" session: stored with
	// sys_session.permanent = 'y' and the long PermanentSessionTTL instead
	// of the idle TTL. Survives Regenerate.
	Permanent bool `json:"permanent,omitempty"`
}

// Store persists sessions in the ISPConfig sys_session table.
type Store struct {
	db  *gorm.DB
	ttl time.Duration
}

// NewStore returns a sys_session-backed store with the given idle TTL
// (DefaultSessionTTL when ttl <= 0).
func NewStore(db *gorm.DB, ttl time.Duration) *Store {
	if ttl <= 0 {
		ttl = DefaultSessionTTL
	}
	return &Store{db: db, ttl: ttl}
}

// Create generates a session id and CSRF token, stores data in sys_session
// and returns the session id. The same id serves as bearer token for
// non-browser API clients. Sessions represent authenticated users only:
// data must carry a non-zero UserID and a non-empty Typ.
func (s *Store) Create(data *SessionData) (string, error) {
	if data.UserID == 0 || data.Typ == "" {
		return "", errors.New("auth: session requires a user id and typ")
	}
	id, err := randomToken()
	if err != nil {
		return "", err
	}
	if data.CSRFToken, err = randomToken(); err != nil {
		return "", err
	}
	payload, err := json.Marshal(data)
	if err != nil {
		return "", fmt.Errorf("encoding session data: %w", err)
	}
	now := time.Now()
	permanent := "n"
	if data.Permanent {
		permanent = "y"
	}
	row := model.SysSession{
		SessionID:   id,
		DateCreated: &now,
		LastUpdated: &now,
		Permanent:   permanent,
		SessionData: string(payload),
	}
	if err := s.db.Create(&row).Error; err != nil {
		return "", fmt.Errorf("creating session: %w", err)
	}
	return id, nil
}

// Get loads a session by id, enforcing the idle TTL: expired sessions are
// deleted and reported as ErrSessionNotFound. Valid lookups touch
// last_updated (sliding expiration). Sessions marked permanent ("stay
// logged in") use the long PermanentSessionTTL instead of the idle TTL.
func (s *Store) Get(id string) (*SessionData, error) {
	if id == "" {
		return nil, ErrSessionNotFound
	}
	var row model.SysSession
	if err := s.db.Where("session_id = ?", id).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrSessionNotFound
		}
		return nil, fmt.Errorf("loading session: %w", err)
	}
	ttl := s.ttl
	if row.Permanent == "y" {
		ttl = PermanentSessionTTL
	}
	if row.LastUpdated == nil || time.Since(*row.LastUpdated) > ttl {
		_ = s.Delete(id)
		return nil, ErrSessionNotFound
	}
	data := &SessionData{}
	if err := json.Unmarshal([]byte(row.SessionData), data); err != nil {
		// Not a go-ispconfig session (e.g. leftover PHP-serialized row).
		return nil, ErrSessionNotFound
	}
	now := time.Now()
	if err := s.db.Model(&model.SysSession{}).Where("session_id = ?", id).
		Update("last_updated", &now).Error; err != nil {
		return nil, fmt.Errorf("touching session: %w", err)
	}
	return data, nil
}

// Regenerate stores data under a fresh session id (and fresh CSRF token)
// and deletes the old session. Call it on privilege changes such as login
// to prevent session fixation.
func (s *Store) Regenerate(oldID string, data *SessionData) (string, error) {
	newID, err := s.Create(data)
	if err != nil {
		return "", err
	}
	if err := s.Delete(oldID); err != nil {
		return "", fmt.Errorf("deleting old session: %w", err)
	}
	return newID, nil
}

// Delete removes a session (logout).
func (s *Store) Delete(id string) error {
	return s.db.Where("session_id = ?", id).Delete(&model.SysSession{}).Error
}

// Cookie builds the HTTP-only SameSite=Strict session cookie (design D4).
// secure should be true when the panel is served over TLS.
func Cookie(sessionID string, secure bool) *http.Cookie {
	return &http.Cookie{
		Name:     SessionCookieName,
		Value:    sessionID,
		Path:     "/",
		HttpOnly: true,
		Secure:   secure,
		SameSite: http.SameSiteStrictMode,
	}
}

// ClearCookie builds an expired session cookie for logout responses.
func ClearCookie(secure bool) *http.Cookie {
	c := Cookie("", secure)
	c.MaxAge = -1
	return c
}

// SessionGetter is the session lookup used by Middleware; *Store implements
// it against sys_session.
type SessionGetter interface {
	// Get returns the session data for id or ErrSessionNotFound.
	Get(id string) (*SessionData, error)
}

// Context keys used by Middleware.
const (
	ctxKeySession    = "auth.session"
	ctxKeySessionID  = "auth.session_id"
	ctxKeyCredential = "auth.credential"
)

// Credential describes how a request authenticated. It is set by the API
// token middleware; a nil value means the request authenticated with a
// session (cookie or session-id bearer), which is the pre-token behaviour.
type Credential struct {
	// TokenID is the remote_user row that authenticated the request.
	TokenID uint32
	// Label is the human name of the token, for logs and errors.
	Label string
	// Scopes are the grants that must cover the route.
	Scopes []string
	// JWT marks a request authenticated by an exchanged JWT rather than by
	// the token itself.
	JWT bool
}

// SetSession attaches an authenticated session to the request context. It
// exists so a credential resolved outside this package (an API token) can
// execute as the sys_user that owns it, with every downstream permission
// check unchanged.
func SetSession(c *echo.Context, data *SessionData) {
	c.Set(ctxKeySession, data)
}

// SetCredential records how the request authenticated.
func SetCredential(c *echo.Context, cred *Credential) {
	c.Set(ctxKeyCredential, cred)
}

// CredentialFromContext returns the API token credential of the request, or
// nil when it authenticated with a session.
func CredentialFromContext(c *echo.Context) *Credential {
	cred, _ := c.Get(ctxKeyCredential).(*Credential)
	return cred
}

// Middleware resolves the session from the request — session cookie for
// browsers, "Authorization: Bearer <session id>" for API clients — and
// attaches it to the context. Cookie-authenticated mutating requests
// (POST/PUT/PATCH/DELETE) must present the session CSRF token in the
// X-CSRF-Token header or the request is rejected with 403 before reaching
// any handler. Requests without a valid session pass through
// unauthenticated (a stale session cookie is cleared on the response);
// combine with RequireAuth on protected routes.
func Middleware(store SessionGetter) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c *echo.Context) error {
			// An API token middleware mounted ahead of this one may already
			// have authenticated the request. Re-resolving the bearer as a
			// session id would only cost a query that cannot match, and the
			// CSRF rule below must not apply to a header credential.
			if FromContext(c) != nil {
				return next(c)
			}
			id, fromCookie := requestSessionID(c.Request())
			if id == "" {
				return next(c)
			}
			data, err := store.Get(id)
			if err != nil {
				if errors.Is(err, ErrSessionNotFound) {
					if fromCookie {
						// Stale cookie: clear it so browsers stop
						// resending a dead session id.
						c.SetCookie(ClearCookie(c.Request().TLS != nil))
					}
					return next(c)
				}
				return err
			}
			if fromCookie && isMutating(c.Request().Method) {
				// An empty header or an empty stored token is rejected
				// outright: ConstantTimeCompare("", "") == 1 would
				// otherwise accept a tokenless request against a
				// malformed session.
				token := c.Request().Header.Get(CSRFHeaderName)
				if token == "" || data.CSRFToken == "" ||
					subtle.ConstantTimeCompare([]byte(token), []byte(data.CSRFToken)) != 1 {
					return echo.NewHTTPError(http.StatusForbidden, "invalid CSRF token")
				}
			}
			c.Set(ctxKeySession, data)
			c.Set(ctxKeySessionID, id)
			return next(c)
		}
	}
}

// RequireAuth rejects unauthenticated requests with 401. Mount it after
// Middleware on every protected route group.
func RequireAuth() echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c *echo.Context) error {
			if FromContext(c) == nil {
				return echo.NewHTTPError(http.StatusUnauthorized, "authentication required")
			}
			return next(c)
		}
	}
}

// FromContext returns the authenticated session attached by Middleware,
// or nil for unauthenticated requests.
func FromContext(c *echo.Context) *SessionData {
	data, _ := c.Get(ctxKeySession).(*SessionData)
	return data
}

// SessionIDFromContext returns the session id attached by Middleware
// (empty for unauthenticated requests). Used by logout.
func SessionIDFromContext(c *echo.Context) string {
	id, _ := c.Get(ctxKeySessionID).(string)
	return id
}

// requestSessionID extracts the session id from the cookie or bearer
// header. fromCookie tells whether CSRF validation applies: bearer clients
// are not cookie-bearing browsers and cannot be victims of CSRF.
func requestSessionID(r *http.Request) (id string, fromCookie bool) {
	if ck, err := r.Cookie(SessionCookieName); err == nil && ck.Value != "" {
		return ck.Value, true
	}
	const prefix = "Bearer "
	if h := r.Header.Get("Authorization"); len(h) > len(prefix) && h[:len(prefix)] == prefix {
		return h[len(prefix):], false
	}
	return "", false
}

// isMutating reports whether an HTTP method requires CSRF protection.
func isMutating(method string) bool {
	switch method {
	case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
		return true
	}
	return false
}

// randomToken returns 32 bytes of crypto/rand entropy hex-encoded
// (64 chars, the exact width of sys_session.session_id).
func randomToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generating token: %w", err)
	}
	return hex.EncodeToString(b), nil
}
