# This sieve script is generated by ISPConfig, any changes made will be overwritten.
# You can create and activate a per-user sieve script (manually or via managesieve),
# which will execute before this.

require ["body", "copy", "date", "envelope", "fileinto", "imap4flags", "mailbox", "regex", "reject", "relational", "subaddress", "vacation", "variables"];


#################################################################
# Autoreply
#################################################################

# Move spam to spam folder
if anyof (header :is ["X-Spam", "X-Spam-Flag"] "Yes", header :matches "X-Spam-Status" "Yes, *") {
  # Stop here so that we do not reply on spams
  stop;
}

if currentdate :value "ge" "iso8601" "2026-08-01T08:00:00" {
if currentdate :value "le" "iso8601" "2026-08-15T18:00:00" {

vacation  :days 1
  :subject "I am 'away' now"
  :addresses ["user1@example.com","alias@example.com","user1@alias-domain.test","alias@alias-domain.test"]
  "Hello,
I will reply 'later'.
Bye";

}
}

