[options]
# message_log = /var/log/getmail.log
message_log_syslog = true
delete = true
read_all = false

[retriever]
type = SimplePOP3Retriever
server = mail.example.com
username = john.doe@example.com
password = s3cr3t

[destination]
type = MDA_external
path = /usr/sbin/sendmail
arguments = ("-i", "-bm", "user1@example.com")
unixfrom = true