spamfilter_wblist-7 {
	priority = 45;
	from = "friend@good.example";
	rcpt = "user1@example.com";
	want_spam = yes;
	apply {
		actions {
			reject = null;
			"add header" = null;
			greylist = null;
			"rewrite subject" = null;
		}
	}
}