global_wblist-3 {
	priority = 30;
	from = "spammer@bad.example";
	apply {
		R_DUMMY = 999.0;
		actions {
			reject = 0.2;
			"add header" = 0.1;
			greylist = 0.1;
			"rewrite subject" = 0.1;
		}
	}
}