global_wblist-5 {
	priority = 31;
	hostname = "relay.partner.example";
	want_spam = yes;
	apply {
		actions {
			reject = null;
			"add header" = null;
			greylist = null;
			"rewrite subject" = null;
		}
	}
}