spamfilter_wblist-8 {
	priority = 42;
	from = "@bad.example";
	rcpt = "user2@example.com";
	apply {
		R_DUMMY = 999.0;
		actions {
			reject = 0.2;
			"add header" = 0.1;
			greylist = 0.1;
			"rewrite subject" = 0.1;
		}
	}
}